#!/usr/bin/env python3
"""
Generate a simple Ninja build file for clang-format
Usage: python generate_format_ninja.py
       ninja -f format.ninja
"""

import os


def find_cpp_files(directories):
    """Find all C/C++ files in given directories"""
    extensions = {".c", ".cpp", ".cc", ".cxx", ".h", ".hpp", ".hxx"}
    files = []

    for directory in directories:
        if os.path.exists(directory):
            for root, dirs, filenames in os.walk(directory):
                for filename in filenames:
                    if any(filename.lower().endswith(ext) for ext in extensions):
                        files.append(os.path.join(root, filename).replace("\\", "/"))

    return sorted(files)


def generate_ninja_file(files, output_file="format.ninja"):
    """Generate simple ninja build file for formatting"""
    with open(output_file, "w") as f:
        f.write("# This file have been generated by generate_format_ninja.py, do NOT edit\n")
        f.write("# Simple Ninja build file for clang-format\n")
        f.write("# Usage: ninja -f format.ninja\n\n")

        f.write("rule format\n")
        f.write("  command = clang-format -i $in\n")
        f.write("  description = Formatting $in\n\n")

        if files:
            f.write("build format: format " + " ".join(files) + "\n")

        f.write("\ndefault format\n")


def main():
    directories = ["src", "include"]

    print(f"Searching for C/C++ files in: {', '.join(directories)}")
    files = find_cpp_files(directories)

    if not files:
        print("No C/C++ files found!")
        return

    print(f"Found {len(files)} files:")
    for file in files:
        print(f"  {file}")

    generate_ninja_file(files)
    print(f"\nGenerated format.ninja with {len(files)} files")
    print("Run 'ninja -f format.ninja' to format all files")


if __name__ == "__main__":
    main()
